package tool;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import static helper.Constants.*;

import helper.MyMessage;
import helper.ProcessFile;
import helper.OrderMethod;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.Scanner;
import javax.swing.UnsupportedLookAndFeelException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

public class WordLookup extends javax.swing.JDialog {

    String DEFAULT_FOLDER = System.getProperty("user.home");

    public WordLookup(String title, boolean modal) {
        initComponents();
        setTitle(title);
        //  setSize(new Dimension(X_SIZE, Y_SIZE));
        inputFileTextField.setText(DEFAULT_FOLDER);
        savingFolderTextField.setText(DEFAULT_FOLDER);
        pack();
        setVisible(true);
        myMessage.setStatus(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printMethodRadioButtonGroup = new javax.swing.ButtonGroup();
        printDirectionRadioGroup = new javax.swing.ButtonGroup();
        purposesButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        inputFileBtn = new javax.swing.JButton();
        savingFolderTextField = new javax.swing.JTextField();
        savingFolderBtn = new javax.swing.JButton();
        inputFileTextField = new javax.swing.JTextField();
        wordListComboBox = new javax.swing.JComboBox<>();
        locationBtn = new javax.swing.JRadioButton();
        printOrderMethod = new javax.swing.JLabel();
        knownWordListLabel = new javax.swing.JLabel();
        printDirectionLabel = new javax.swing.JLabel();
        increaseRadioButton = new javax.swing.JRadioButton();
        decreaseRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lookupRadioButton = new javax.swing.JRadioButton();
        countRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        outputViewFileBtn = new javax.swing.JButton();
        occuranceBtn = new javax.swing.JRadioButton();
        alphabettaBtn = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        OKButton = new javax.swing.JButton();
        messageField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2147483647, 400));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(634, 320));
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(761, 200));

        inputFileBtn.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        inputFileBtn.setText("Source");
        inputFileBtn.setToolTipText("Select or Enter File Name or URL");
        inputFileBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileBtnActionPerformed(evt);
            }
        });

        savingFolderBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        savingFolderBtn.setText("Output Path");
        savingFolderBtn.setToolTipText("Enter Output Path");
        savingFolderBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savingFolderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingFolderBtnActionPerformed(evt);
            }
        });

        wordListComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        wordListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "400k", "100k", "20k", "10k", "none" }));
        wordListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordListComboBoxActionPerformed(evt);
            }
        });

        printMethodRadioButtonGroup.add(locationBtn);
        locationBtn.setSelected(true);
        locationBtn.setText("Location");
        locationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBtnActionPerformed(evt);
            }
        });

        printOrderMethod.setText("Print Order Method");

        knownWordListLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        knownWordListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        knownWordListLabel.setText("Vocabulary Level");

        printDirectionLabel.setText("Direction");

        printDirectionRadioGroup.add(increaseRadioButton);
        increaseRadioButton.setSelected(true);
        increaseRadioButton.setText("Incr");
        increaseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseRadioButtonActionPerformed(evt);
            }
        });

        printDirectionRadioGroup.add(decreaseRadioButton);
        decreaseRadioButton.setText("Decr");
        decreaseRadioButton.setEnabled(false);
        decreaseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Purposes");

        purposesButtonGroup.add(lookupRadioButton);
        lookupRadioButton.setSelected(true);
        lookupRadioButton.setText("lookup");
        lookupRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupRadioButtonActionPerformed(evt);
            }
        });

        purposesButtonGroup.add(countRadioButton);
        countRadioButton.setText("Occurr#");
        countRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Translated Lang");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chinese", "Default" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        outputViewFileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outputViewFileBtn.setText("View ...");
        outputViewFileBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        outputViewFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputViewFileBtnActionPerformed(evt);
            }
        });

        printMethodRadioButtonGroup.add(occuranceBtn);
        occuranceBtn.setText("Occurr#");
        occuranceBtn.setEnabled(false);
        occuranceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occuranceBtnActionPerformed(evt);
            }
        });

        printMethodRadioButtonGroup.add(alphabettaBtn);
        alphabettaBtn.setText("Alpha");
        alphabettaBtn.setEnabled(false);
        alphabettaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alphabettaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(savingFolderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(knownWordListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(561, 561, 561)
                                .addComponent(locationBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(wordListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                        .addComponent(outputViewFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(savingFolderTextField)
                                    .addComponent(inputFileTextField)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lookupRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printOrderMethod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printDirectionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(increaseRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decreaseRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(occuranceBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alphabettaBtn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(knownWordListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputViewFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingFolderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(locationBtn)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(increaseRadioButton)
                    .addComponent(printDirectionLabel)
                    .addComponent(printOrderMethod)
                    .addComponent(lookupRadioButton)
                    .addComponent(jLabel2)
                    .addComponent(countRadioButton)
                    .addComponent(decreaseRadioButton)
                    .addComponent(occuranceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alphabettaBtn)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {inputFileBtn, savingFolderBtn});

        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        OKButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OKButton.setText("OK");
        OKButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        messageField.setEditable(false);
        messageField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        messageField.setForeground(new java.awt.Color(237, 10, 10));
        messageField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        messageField.setText("Welcome To VocabLookup");
        messageField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        messageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageField)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        String fileUrl = inputFileTextField.getText();
        Scanner fileScanner = null;
        String urlText = null;
        myMessage = new MyMessage(messageField);
        myMessage.setStatus(0);
        Thread t = new Thread(myMessage);
        t.start();
        try {
            Document doc = Jsoup.connect(fileUrl)
                    .userAgent("Firefox")
                    .timeout(3000)
                    .get();
            urlText = doc.body().text();
            messageField.setText("Wait ...");
            // read from your scanner
        } catch (IOException | IllegalArgumentException ex) {
            // there was some connection problem, or the file did not exist on the server,
            // or your URL was not in the right format.
            // think about what to do now, and put it here.

            File file = new File(inputFileTextField.getText());
            if (!file.exists() || !file.isFile()) {
                messageField.setText("Please select a valid input file.");
                myMessage.setStatus(2);
                return;
            } else {
                try {
                    messageField.setText("Wait ...");
                    fileScanner = new Scanner(file);
                } catch (FileNotFoundException ex1) {
                    myMessage.setStatus(2);
                    messageField.setText("File not found ...");
                    return;
                }
            }
        }
        myMessage.setStatus(1);
        messageField.setText("In Process ... ");
        try {
            ProcessFile process;
            process = new ProcessFile(urlText, fileScanner, (String) wordListComboBox.getSelectedItem() + ".txt",
                    savingFolderTextField.getText(), getOrderMethod(), increaseRadioButton.isSelected());
            if (lookupRadioButton.isSelected()) {
                process.lookup();
            } else {
                process.sort();
            }
            myMessage.setStatus(2);
            messageField.setText("Lookup is done!");
        } catch (Exception e) {
            myMessage.setStatus(2);
            messageField.setText("Error Occurs, please verify source or output path ...");
        }

    }//GEN-LAST:event_OKButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void inputFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(inputFileTextField.getText()));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            try {
                String proj = f.toString();
                inputFileTextField.setText(proj);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_inputFileBtnActionPerformed

    private void savingFolderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingFolderBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(savingFolderTextField.getText()));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            try {
                String proj = f.toString();
                savingFolderTextField.setText(proj);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_savingFolderBtnActionPerformed

    private void lookupRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupRadioButtonActionPerformed
        // TODO add your handling code here:
        locationBtn.setEnabled(true);
        locationBtn.setSelected(true);
        occuranceBtn.setEnabled(false);
        alphabettaBtn.setEnabled(false);
        decreaseRadioButton.setEnabled(false);
        increaseRadioButton.setText(INCREASE);
        decreaseRadioButton.setText(DECREASE);
    }//GEN-LAST:event_lookupRadioButtonActionPerformed

    private void countRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countRadioButtonActionPerformed
        // TODO add your handling code here:
        locationBtn.setEnabled(false);
        occuranceBtn.setEnabled(true);
        alphabettaBtn.setEnabled(true);
        occuranceBtn.setSelected(true);
        decreaseRadioButton.setEnabled(true);
    }//GEN-LAST:event_countRadioButtonActionPerformed

    private void alphabettaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alphabettaBtnActionPerformed
        // TODO add your handling code here:
        increaseRadioButton.setText(A_TO_Z);
        decreaseRadioButton.setText(Z_TO_A);
    }//GEN-LAST:event_alphabettaBtnActionPerformed

    private void occuranceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occuranceBtnActionPerformed
        // TODO add your handling code here:
        increaseRadioButton.setText(INCREASE);
        decreaseRadioButton.setText(DECREASE);
    }//GEN-LAST:event_occuranceBtnActionPerformed

    private void increaseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_increaseRadioButtonActionPerformed

    private void outputViewFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputViewFileBtnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(savingFolderTextField.getText()));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            try {
                BufferedReader br = new BufferedReader(new FileReader(f));
                ViewFileDialog viewFileDialog = new ViewFileDialog(this);
                viewFileDialog.getTextArea().read(br, null);
                viewFileDialog.setVisible(true);
                viewFileDialog.show();
                br.close();
            } catch (HeadlessException | IOException ex) {
                System.out.println("Fail to view file: " + ex);
            }
        }
    }//GEN-LAST:event_outputViewFileBtnActionPerformed

    private void wordListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordListComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordListComboBoxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void locationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationBtnActionPerformed

    private void decreaseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decreaseRadioButtonActionPerformed

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageFieldActionPerformed

    private OrderMethod getOrderMethod() {
        OrderMethod orderMethod = OrderMethod.LOCATION;
        if (occuranceBtn.isSelected()) {
            orderMethod = OrderMethod.OCCURANCE;
        } else if (alphabettaBtn.isSelected()) {
            orderMethod = OrderMethod.ABC;
        }
        return orderMethod;
    }

    public static void main(String argv[]) {
        try {
            WordLookup tool;
            tool = new WordLookup(TITLE, true);

            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.invokeAndWait(() -> {
                tool.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        tool.dispose();
                        System.exit(0);
                    }
                });

            });
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | InterruptedException | InvocationTargetException | UnsupportedLookAndFeelException ex) {
            System.out.println("Exception occurs: " + ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JRadioButton alphabettaBtn;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton countRadioButton;
    private javax.swing.JRadioButton decreaseRadioButton;
    private javax.swing.JRadioButton increaseRadioButton;
    private javax.swing.JButton inputFileBtn;
    private javax.swing.JTextField inputFileTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel knownWordListLabel;
    private javax.swing.JRadioButton locationBtn;
    private javax.swing.JRadioButton lookupRadioButton;
    private javax.swing.JTextField messageField;
    private javax.swing.JRadioButton occuranceBtn;
    private javax.swing.JButton outputViewFileBtn;
    private javax.swing.JLabel printDirectionLabel;
    private javax.swing.ButtonGroup printDirectionRadioGroup;
    private javax.swing.ButtonGroup printMethodRadioButtonGroup;
    private javax.swing.JLabel printOrderMethod;
    private javax.swing.ButtonGroup purposesButtonGroup;
    private javax.swing.JButton savingFolderBtn;
    private javax.swing.JTextField savingFolderTextField;
    private javax.swing.JComboBox<String> wordListComboBox;
    private MyMessage myMessage;
    // End of variables declaration//GEN-END:variables
}
